name: Build Markdown to HTML

on:
  push:
    paths:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Convert Markdown to HTML (example using pandoc)
      run: |
        sudo apt-get install pandoc
        mkdir -p _build/html
        for file in $(find . -name "*.md"); do
            pandoc $file -o ./_build/html/${file%.md}.html
        done
    
    - name: Commit generated HTML files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add _build/html/*.html
        git commit -m "Add generated HTML files"

    # Deploy to GitHub Pages (push to the main branch)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        branch: main
