name: Build Markdown to HTML

on:
  push:
    paths:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Generate index.md
      run: |
        echo "# My HTML Files" > index.md
        for file in $(find . -name "*.md" -not -name "index.md"); do
            echo "- [${file%.md}](${file%.md}.html)" >> index.md
        done

    - name: Convert Markdown to HTML
      run: |
        sudo apt-get install pandoc
        mkdir -p _build/html
        for file in $(find . -name "*.md"); do
            pandoc $file -o ./_build/html/${file%.md}.html
        done
    
    - name: Commit generated HTML files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add _build/html/*.html
        git commit -m "Add generated HTML files"

    - name: Create .nojekyll file
      run: touch _build/html/.nojekyll

    # Deploy to GitHub Pages (push to the gh-pages branch)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./_build/html
        publish_branch: gh-pages