name: Build and Deploy Jupyter Book

on:
  push:
    paths:
    - '**.md'
    - '!mynewbook/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
        
    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install Jupyter Book and dependencies
      run: |
        python -m pip install --upgrade pip
        
        # Check if jupyter-book is installed
        if ! command -v jupyter-book &> /dev/null; then
            pip install jupyter-book
        fi

    # Copy markdown files (except README.md) from root to the Jupyter Book directory
    # Prepare files for Jupyter Book by ensuring a match between root and mynewbook/
    - name: Prepare files for Jupyter Book
      run: |
        # Remove markdown files in mynewbook/ (assuming no integral .md files to Jupyter Book in there)
        rm -f mynewbook/*.md
        
        # Copy markdown files (except README.md) from root to the mynewbook/ directory
        for file in *.md; do
            if [ "$file" != "README.md" ]; then
                cp $file mynewbook/
            fi
        done

    # Generate TOC (you can skip this if you manually maintain _toc.yml)
    - name: Generate TOC
      run: |
        jupyter-book toc from-project mynewbook > mynewbook/_toc.yml

    # Build the Jupyter Book
    - name: Build Jupyter Book
      run: |
        jupyter-book build mynewbook
    
    # Deploy to GitHub Pages (push to the gh-pages branch)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./mynewbook/_build/html
        publish_branch: gh-pages
