name: Build Markdown to HTML

on:
  push:
    paths:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # Ensures we use the token we provide for push, not GITHUB_TOKEN
        fetch-depth: 0 # Get all history so we can push correctly.

    - name: Convert Markdown to HTML (example using pandoc)
      run: |
        sudo apt-get install pandoc
        for file in $(find . -name "*.md"); do
            pandoc $file -o ${file%.md}.html
        done
    
    - name: Commit generated HTML files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.html
        git commit -m "Add generated HTML files"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: ${{ github.main }}
