name: Example workflow with push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # This step sets up the Git client with the PAT
    - name: Set up Git client
      env:
        MY_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote set-url origin https://x-access-token:$MY_TOKEN@github.com/MufengNiu/JupyerTest.git
        
    - name: Make changes and push
      run: |
        echo "This is a new line" >> example.txt
        git add example.txt
        git commit -m "Add a new line from GitHub Actions"
        git push https://x-access-token:$MY_TOKEN@github.com/MufengNiu/JupyerTest.git main